/-
Copyright (c) 2026 Nicholas Bulka. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
Authors: Nicholas Bulka
-/
import Lean

/-!
comparator/GeneratePrintAxioms.lean — a developer tool, not part of the build.

If you prefer a checked-in `#print axioms` transcript over the self-reading audit in
`PrintAxioms.lean`, this regenerates that transcript from `comparator.json`, so the two lists
cannot drift apart:

    lake env lean comparator/GeneratePrintAxioms.lean

It writes the file named in the `#emit_print_axioms` invocation at the bottom.  Nothing here
imports the development, so it is cheap to run.
-/

open Lean Elab Command

/-- `#emit_print_axioms "comparator.json" "Solution" "comparator/PrintAxiomsGenerated.lean"` —
write a `#print axioms` transcript covering exactly the theorems named in the config. -/
elab "#emit_print_axioms" cfg:str solMod:str out:str : command => do
  let path : System.FilePath := cfg.getString
  unless ← path.pathExists do
    throwError "comparator config not found: {path}"
  let j ← IO.ofExcept (Json.parse (← IO.FS.readFile path))
  let names ← match j.getObjValAs? (Array String) "theorem_names" with
    | .ok a => pure a
    | .error e => throwError "{path}: field 'theorem_names': {e}"
  let header :=
    "/-\nGENERATED by comparator/GeneratePrintAxioms.lean from " ++ cfg.getString ++
    " -- do not edit by hand.\nRun:  lake env lean " ++ out.getString ++ "\n" ++
    "Every line must print exactly:  ... depends on axioms: [propext, Classical.choice, " ++
    "Quot.sound]\n-/\nimport " ++ solMod.getString ++ "\n\n"
  let body := String.join (names.toList.map fun n => "#print axioms " ++ n ++ "\n")
  IO.FS.writeFile out.getString (header ++ body)
  logInfo m!"wrote {out.getString} ({names.size} declaration(s))"

#emit_print_axioms "comparator.json" "Solution" "comparator/PrintAxiomsGenerated.lean"
